CartoDB/Windshaft

- lib/windshaft/renderers/render_cache.js
- test/unit/render_cache.test.js
> Remove cache entry if configuration for token is not found

- lib/windshaft/backends/map.js
- lib/windshaft/backends/map_validator.js
- lib/windshaft/models/mapconfig.js
- lib/windshaft/server.js
- All layers validation happens in MapValidator
- Torque layers metadata retrieval happens in Map Backend
> Create layergroup improvements

- lib/windshaft/backends/map.js
> Use datasource for layer when retrieving attributes

- lib/windshaft/renderers/renderer_factory.js
- It will be simpler once non-token instantiation is the only option mapnik factory
> Remove as much duplication as possible in renderer factory

- lib/windshaft/controllers/map.js
- lib/windshaft/controllers/tiles.js
> Reuse getTileOrGrid between controllers until old api is removed

- Makefile
- lib/windshaft/controllers/map.js
- lib/windshaft/server.js
- test/unit/controllers/tile_stats.test.js
- test/unit/windshaft.test.js
it's no longer used from any other place
> Moves finalizeGetTileOrGrid to mapcontroller

- doc/MapConfig-1.3.0.md
- lib/windshaft/renderers/http/factory.js
- lib/windshaft/renderers/http/renderer.js
> Adds tms option in http layers to invert Y axis in TMS services

- NEWS.md
- lib/windshaft/renderers/base_adaptor.js
- lib/windshaft/renderers/http/renderer.js
- lib/windshaft/renderers/mapnik/adaptor.js
- test/acceptance/wrap.js
> Wrap x coordinate based on zoom level to avoid negative x coordinates

- NEWS.md
- lib/windshaft/backends/map_validator.js
- lib/windshaft/server.js
> Do not profile during map validation

- examples/readme_server.js
The "test" environment is incorrect for development, and the port constant should be configurable.
> Use development settings and port constant

- lib/windshaft/renderers/blend/factory.js
- test/acceptance/static_maps.js
The rest of the errors will be raised yet
Closes #325
> Handles coordinates out of range errors returning an empty image

- NEWS.md
- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/http/renderer.js
- test/acceptance/blend_http_timeout.js
> Checks for ETIMEDOUT error code so timeouts do not turn into empty image in http layers

- lib/windshaft/renderers/torque/factory.js
> Corrects checking for number types in Torque

- NEWS.md
- lib/windshaft/renderers/base_adaptor.js
- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/blend/renderer.js
- lib/windshaft/renderers/mapnik/adaptor.js
- lib/windshaft/stats/reporter/renderer.js
Exposes renderers stats in Blend renderer and implements a getStats in adaptors.
> Renderer stats for pool and cache now reports from all renderers

- NEWS.md
- lib/windshaft/renderers/render_cache.js
> Honor RenderCache ttl option

- config/environments/development.js
- config/environments/test.js
- lib/windshaft/renderers/renderer_factory.js
- lib/windshaft/renderers/torque/factory.js
- lib/windshaft/renderers/torque/psql_adaptor.js
- lib/windshaft/server.js
Makes torque renderer psql adaptor to accept pool params from config
This closes #380
> Torque pool params

- NEWS.md
- package.json
> Upgrades mapnik to 1.4.15-cdb6

- NEWS.md
- package.json
> Upgrades tilelive-mapnik to not cache solid grids

- config/environments/development.js
- lib/windshaft/backends/map.js
- lib/windshaft/metadata/empty-layer-metadata.js
- lib/windshaft/metadata/index.js
- lib/windshaft/metadata/layer-metadata.js
- lib/windshaft/metadata/mapnik-layer-metadata.js
- lib/windshaft/metadata/torque-layer-metadata.js
- test/acceptance/multilayer_metadata.js
- test/acceptance/multilayer_metadata_stats.js
> Metadata refactor

- package.json
> Upgrade grainstore version

- lib/windshaft/backends/widget.js
- lib/windshaft/models/filters/query_builder.js
- lib/windshaft/models/filters/range.js
- lib/windshaft/models/widgets/histogram.js
- test/acceptance/widgets/histogram.js
Widget check column type to determine if type casting is required
> Widgets histogram improvements

- lib/windshaft/renderers/mapnik/geojson_renderer.js
- lib/windshaft/renderers/mapnik/geojson_template.sql
- test/support/geojson_value.js
@dgaubert @rochoa 
As discussed with @javisantana, we're not specifying dynamically buffer size for now, so it's currently a constant set to 32px.
> Geojson buffer

- NEWS.md
- lib/windshaft/models/widgets/histogram.js
- package.json
- test/acceptance/widgets/histogram.js
> Histogram uses bins option to set the number of buckets

- NEWS.md
- lib/windshaft/models/widgets/histogram.js
- test/acceptance/widgets/histogram.js
> Histogram can be retrieved with a fix number of bins

- lib/windshaft/renderers/mapnik/geojson_template.sql
- test/acceptance/geojson.js
- test/support/geojson_value.js
Fix #436 
kudos to @rochoa
cc @rambo
> Geojson make valid

- lib/windshaft/renderers/mapnik/geojson_renderer.js
- lib/windshaft/renderers/mapnik/geojson_template.sql
Fixes https://github.com/CartoDB/Windshaft/issues/439
@javisantana
> Passes buffer size calculation to SQL query

- lib/windshaft/metadata/mapnik-layer-metadata.js
> Passes cartocss in metadata

- lib/windshaft/utils/cartocss_utils.js
> Use carto parser to extract relevant selectors from cartocss

- lib/windshaft/utils/cartocss_utils.js
- test/unit/utils/cartocss_utils.test.js
> Do not direct access to array elements, iterate over them

- lib/windshaft/utils/geojson_utils.js
- test/acceptance/geojson.js
- test/unit/utils/geojson.js
> Handle interactivity columns as they might be arrays or strings

- NEWS.md
- lib/windshaft/renderers/mapnik/geojson_template.sql
- test/acceptance/geojson.js
It might fail for some tiles but it's way better performance wise.
> Remove ST_MakeValid from GeoJSON renderer

- lib/windshaft/utils/geojson_utils.js
- test/unit/utils/geojson.js
Fixes [Windshaft-cartodb#427](https://github.com/CartoDB/Windshaft-cartodb/issues/427)
cc @rochoa
> Geojson dataview columns

- lib/windshaft/utils/geojson_utils.js
- test/unit/utils/geojson.js
> Handled "columns" property in layer options of map-config

- NEWS.md
- lib/windshaft/renderers/mapnik/geojson_renderer.js
- lib/windshaft/utils/cartocss_utils.js
- package.json
> Adds support for buffer-size CartoCSS Map property in geojson tiles

- NEWS.md
- lib/windshaft/models/mapconfig.js
- test/unit/mapconfig.test.js
please @rochoa could you CR this?
PS: this PR helps to get the layer id w/o instantiate a MapConfig.
> Mapconfig layer

- lib/windshaft/models/datasource.js
- lib/windshaft/models/mapconfig.js
- test/unit/mapconfig.test.js
Fixes #528 and supersedes #529 
Roughly, https://github.com/CartoDB/Windshaft/commit/e0f6b49b3e8aa2c8719ae72f6a8a7f4e40e0e628 is what @rochoa meant.
cc/ @strk
> Allow overriding layer srid

- package.json
> Add dgaubert as contributor

- lib/windshaft/server.js
- test/acceptance/server.js
> Nostalgically adding John Rambo

- NEWS.md
- lib/windshaft/renderers/mapnik/factory.js
- test/unit/renderers/mapnik-factory.test.js
> Don't default formats in formatMetatile configuration

- doc/MapConfig-1.6.0.md
- lib/windshaft/models/mapconfig.js
- lib/windshaft/renderers/mapnik/factory.js
- package.json
- test/unit/models/mapconfig-buffer-size.test.js
- test/unit/renderers/mapnik-factory.test.js
> [tilelive-* release required] Use different buffer-size values for different tile formats

- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/mapnik/factory.js
- lib/windshaft/renderers/pg-mvt/factory.js
- lib/windshaft/renderers/renderer_factory.js
- lib/windshaft/utils/layer_filter.js
It handles aliases: all, mapnik, etc. It also casts numbers accordingly.
> Unify layer filtering logic in layer_filter

- .travis.yml
Target cartoimages instead of dmanzanares docker account
> Fix docker repo path

- .travis.yml
- Dockerfile
- lib/windshaft/renderers/pg-mvt/renderer.js
- package.json
Minor dependencies added to improve flexibility.
Removal of the `expose 5858` to avoid clashing between multiple dockers on host
> Better docker

- doc/MapConfig-1.7.0.md
- doc/MapConfig-specification.md
This documents the new vector-only layers; see #575
> Upgrade MapConfig spec to 1.7.0

- NEWS.md
- examples/http/server.js
- lib/windshaft/index.js
- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/blend/renderer.js
- lib/windshaft/renderers/http/renderer.js
- lib/windshaft/renderers/mapnik/factory.js
- lib/windshaft/renderers/plain/color_renderer.js
- lib/windshaft/renderers/plain/factory.js
- lib/windshaft/renderers/plain/image_renderer.js
- package.json
- test/acceptance/layer-filtering-regressions.js
- test/acceptance/multilayer.js
- test/acceptance/mvt.js
- test/acceptance/server_gettile.js
- test/acceptance/static_maps.js
- test/acceptance/vector-layergroup.js
- test/acceptance/zoom-min-max.js
- test/integration/renderers/plain_image_renderer.js
- test/integration/static_maps.js
- test/support/assert.js
- test/support/server_options.js
- test/support/test_client.js
@dgaubert in this branch I preventively revert the node-mapnik related changes as per our discussion. But believe me, I'll come back stronger than ever! :muscle: 
Basically I did `git revert` on the corresponding commits.
> Revert carto mapnik changes

- NEWS.md
- examples/http/server.js
- lib/windshaft/index.js
- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/blend/renderer.js
- lib/windshaft/renderers/http/renderer.js
- lib/windshaft/renderers/mapnik/factory.js
- lib/windshaft/renderers/plain/color_renderer.js
- lib/windshaft/renderers/plain/factory.js
- lib/windshaft/renderers/plain/image_renderer.js
- package.json
- test/acceptance/layer-filtering-regressions.js
- test/acceptance/multilayer.js
- test/acceptance/mvt.js
- test/acceptance/server_gettile.js
- test/acceptance/static_maps.js
- test/acceptance/vector-layergroup.js
- test/acceptance/zoom-min-max.js
- test/integration/renderers/plain_image_renderer.js
- test/integration/static_maps.js
- test/support/assert.js
- test/support/server_options.js
- test/support/test_client.js
This is pretty similar to what was done in https://github.com/CartoDB/Windshaft/pull/586 and that I reverted in https://github.com/CartoDB/Windshaft/pull/589 in order not to block anyone.
> Upgrade mapnik to @carto/mapnik 3.6.2-carto.2

- NEWS.md
- config/environments/development.js
- doc/MapConfig-1.7.0.md
- lib/windshaft/renderers/mapnik/factory.js
- package.json
- test/unit/render_cache.test.js
I'm kind of worry about the testing part since I'm not sure what the appropriate way to test this is (render should be the same or really similar).
If someone can have a look at the code it'd great, but feel free to ignore it.
> Support layer 'cache-features' in Mapnik/CartoDB layers

- NEWS.md
- config/environments/development.js
- lib/windshaft/renderers/mapnik/factory.js
- package.json
- test/acceptance/raster.js
- test/integration/static_maps.js
PR to add the mapnik metrics option in Windshaft. For now set globally in the configuration file.
> Add mapnik metrics option

- NEWS.md
- package.json
Related to https://github.com/CartoDB/Windshaft-cartodb/pull/893
Will require publishing a new package and updating Windshaft-cartodb again
> Update Request to 2.85.0

- Dockerfile
- NEWS.md
We need Redis v4 for rate limits feature.
> Redis v4 in Dockerfile

- NEWS.md
- package.json
- test/acceptance/mvt.js
Test reproducing the interaction between `false` and integer columns
~~Weirdly enough, `TRUE` seems to be always transformed into `1`, never `true`.~~
cc/ @oleurud @rochoa
> Add test with mvt bug

- .npmignore
- NEWS.md
I'm figuring out how to test it... If `Windshaft-cartodb` tests pass with it then I'll be fine with it.
This closes #626
> Add .npmignore #626

- NEWS.md
- package-lock.json
- package.json
Upgrade: 
- `tilelive-mapnik` to version `0.6.18-cdb19`
- `tilelive-bridge` to version `2.5.1-cdb12`
> Upgrade tilelive-mapnik & tilelive-bridge

- test/acceptance/limits.js
- test/acceptance/mvt.js
- test/acceptance/vector-layergroup.js
- test/acceptance/zoom-min-max.js
> Always run Postgis 2.4+ tests

- lib/windshaft/backends/map_validator.js
- lib/windshaft/metadata/layer-metadata.js
- lib/windshaft/renderers/blend/factory.js
- lib/windshaft/renderers/blend/renderer.js
- package-lock.json
- package.json
- test/acceptance/multilayer_error_cases.js
Use promises instead.
Fixes #693
> Remove queue-async as a project dependency

- NEWS.md
- lib/windshaft/renderers/pg-mvt/renderer.js
- package-lock.json
- package.json
- test/acceptance/torque.js
Use the new parameter in PSQL.query to remove the need to have an extra event to handle the pg-mvt timeouts.
> [WIP] Use node-cartodb-psql with timeout

- README.md
Missing information how to get it built on MacOS
> Clarify MacOS deps on Read.me
