lib/windshaft/renderers/http/factory.js
package.json
test/unit/renderers/http_factory.test.js

- it's backwards compatible, although it is no longer O(1) (it doesn't matter!)
- there is an skipped test because we want to solve that before enabling it

Enable regex matching in valid url templates for http renderer

---

examples/readme_server.js

This uses the same pattern from `test/performance/test_server.js` to set `global.environment`.
Resolves #288

Add global.environment variables to readme_server.js

---

scripts/check-node-canvas.sh
scripts/install.sh

The Bourne shell doesn't support `[[` and throws errors when not executed under bash.
I found this bug by running `make` in the root project directory in Ubuntu 14.04 in the last released version, but I see that the shell is being set in the `Makefile` now. This no longer affects `make`, but should still be corrected.
```console
vagrant@vagrant-ubuntu-trusty-64:~/Windshaft$ ./scripts/install.sh
./scripts/install.sh: 3: ./scripts/install.sh: [[: not found
```

Properly use bash instead of sh

---

NEWS.md
lib/windshaft/renderers/torque/png_renderer.js
lib/windshaft/renderers/torque/renderer.js
package.json
test/acceptance/blend.js
test/acceptance/torque_png.js

As tiles in server are rendered individually some features that belong to a
tile in {x: 0, y: 0} but are close to the edge should be rendered in also in
tile, let's say, {x: 1, y: 0} however that last time won't have the data
because it is outside of its bounding box. Adding a bit of buffer to the
bounding box allows to render those features from others' tiles data.
Torque's windshaft provider uses by default a Uint8Array for the coordinates
so it is not possible to represent values different than 0..255 that's why we
force the use of Int16Array to be able to represent negative numbers and values
bigger than 255.
The torque renderer now accepts an options parameter that allows to setup the
buffer size for the query, by default it uses buffer-size=0. So existing users
will keep the …

Torque server side renderer using buffer-size

---

NEWS.md
doc/MapConfig-1.1.0.md
doc/MapConfig-1.2.0.md
examples/viewer/leaflet.css
examples/viewer/leaflet.ie.css
lib/windshaft/models/mapconfig.js
lib/windshaft/renderers/README
lib/windshaft/renderers/render_cache.js
lib/windshaft/renderers/torque/factory.js
lib/windshaft/server.js
lib/windshaft/storages/mapstore.js
test/README.md
test/acceptance/attributes.js
test/acceptance/multilayer.js
test/acceptance/raster.js
test/acceptance/server.js
test/acceptance/server_gettile.js
test/acceptance/torque.js
test/performance/README
test/performance/benchmark.js
test/performance/test_server.js
test/support/assert.js
test/support/server_options.js
test/unit/mapstore.test.js
test/unit/render_cache.test.js
test/unit/torque.test.js

I've gone through these by hand and made sure that all tests pass, but it's worth mentioning that this was done automagically with:
``` shell
find . -type f \( \
-name '*.js' -o -name '*.css' -o -name '*.md' -o -name 'README' \
\) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
```
The only place where I could imagine this being a problem would be [hard line breaks in Markdown](http://spec.commonmark.org/0.17/#hard-line-break), but there aren't any of those in this repo.

Remove trailing whitespace

---

lib/windshaft/controllers/map.js

that way static controller can handle all URL associated to it

Skip layer handler in map controller if token === 'static'

---

test/unit/render_cache.test.js

Unless the PostgreSQL [host-based authentication configuration](http://www.postgresql.org/docs/9.1/static/auth-pg-hba-conf.html) has a matching record with an auth-mode of [`trust`](http://www.postgresql.org/docs/9.3/static/auth-methods.html#AUTH-TRUST), PostgreSQL throws an authentication failure when trying to connect without a password and [Mocha's equality assertion](https://github.com/CartoDB/Windshaft/blob/09e9d4bfb90aae832b6da5fa048ff389c0489396/test/unit/render_cache.test.js#L221) fails.
Here are the  original errors, caused by the `md5` auth-mode in the `host all all 0.0.0.0/0 md5` record.
Obligatory stacktrace.
I've read through #59, #171, and mapnik/mapnik#2179 to make sure that `renderer_cache.test.js` wasn't meant to cache the password somehow, but it might be worth having …

Authenticate as "test_ws_publicuser" with password

---

NEWS.md
doc/MapConfig-specification.md
doc/Multilayer-API.md
lib/windshaft/backends/map.js
lib/windshaft/cache/cache_entry.js
lib/windshaft/models/mapconfig.js
lib/windshaft/renderers/base_adaptor.js
lib/windshaft/renderers/blend/renderer.js
lib/windshaft/renderers/http/fallback_renderer.js
lib/windshaft/renderers/http/renderer.js
lib/windshaft/renderers/mapnik/adaptor.js
lib/windshaft/renderers/plain/renderer.js
lib/windshaft/server.js
test/acceptance/multilayer.js
test/acceptance/multilayer_interactivity.js
test/acceptance/torque.js

See https://github.com/CartoDB/Windshaft/issues/338
Multilayer-API.md contains information about the changes introduced by this.
Keeps backwards compatibility for torque metadata.

Layergroup creation returns metadata for all layers

---

lib/windshaft/backends/map.js

That way we avoid the overhead of creating renderers just for metadata
Some notes about renderer creation and RenderCache:
- getMetadata is a expensive operation because it requires a renderer
- Renderers are cached in RenderCache
- Renderer creation and recreation is based on the existence of a key
in the RenderCache and a cache buster associated to the request and
if the Renderer already exists
- MapValidation follows a similar approach but if the MapConfig key
was already in Redis it does not validate again the map so it does
not need to create the renderers again. So the number of times the
validation is actually happening, and thus renderer creation, is
way lower than metadata use case.
- Metadata was happening for every single layergroup creation
- One of the biggest issues is the …

Renderer metadata only called for torque layers

---

NEWS.md
lib/windshaft/backends/map.js
lib/windshaft/backends/map_validator.js
lib/windshaft/controllers/map.js
lib/windshaft/controllers/static_maps.js
lib/windshaft/server.js
test/acceptance/attributes.js
test/acceptance/multilayer.js
test/acceptance/multilayer_error_cases.js
test/acceptance/regressions.js
test/acceptance/retina.js
test/acceptance/server.js
test/acceptance/torque.js

Replaces `error=>String` with `errors=>Array` error responses
Closes #351

Unify error response format

---

lib/windshaft/renderers/torque/factory.js
test/acceptance/torque.js

Fixes #150 
Sending a malformed CSS style in the query will make Windshaft respond with a JSON error like the following:
```javascript
{
errors: [
"Unexpected type for property '-torque-aggregation-function', expected string"
]
}
```
@rochoa what do you think?
cc @javisantana

Checks the type of torque-specific CSS rules

---

NEWS.md
lib/windshaft/renderers/base_adaptor.js
lib/windshaft/renderers/blend/renderer.js
lib/windshaft/renderers/http/fallback_renderer.js
lib/windshaft/renderers/plain/renderer.js
lib/windshaft/renderers/torque/png_renderer.js
package.json

- Uses [cartodb/node-canvas@1.2.7-cdb1](https://github.com/CartoDB/node-canvas/releases/tag/1.2.7-cdb1)
- Implements close mechanism for torque renderer to free canvas' images
- Base adaptor exposes and calls renderers' close if available
- Blend renderer calls close on all renderers

Improve renderers draining from renderer cache

---

NEWS.md
lib/windshaft/renderers/render_cache.js
package.json

That behaviour applies only when gc extension is enabled with `--expose_gc` flag.

RendererCache invoke gc 1 out of 10 times it runs

---

lib/windshaft/renderers/torque/factory.js
lib/windshaft/renderers/torque/renderer.js
lib/windshaft/renderers/torque/substitution_tokens.js
test/acceptance/torque.js
test/unit/renderers/torque_substitutions_tokens.js

Supported substitution tokens are:
- !bbox! spatial filter applied in the tile
- !pixel_width! width of a pixel in geographical units
- !pixel_height! height of a pixel in geographical units
- !scale_denominator! display pixel size
They have the same semantics than the ones in Mapnik's PostGIS plugin. For
more information about them check:
https://github.com/mapnik/mapnik/wiki/PostGIS#advanced-usage
Check https://github.com/mapnik/mapnik/wiki/ScaleAndPpi for more information
about scale_denominator.

Adds support for substitution tokens in Torque

---

.travis.yml
lib/windshaft/renderers/mapnik/geojson_template.sql

@dgaubert let's integrate this in the mapconfig+geojson branch so that we reduce the stress of the renderer right away? It's still missing things like simplifying features and so on but this change reliefs the renderer from a massive burden of redundant features.
cc @rochoa

Cuts geojson geometries into tiles to avoid a lot of redundancy in client

---

NEWS.md
package.json

Stuff that depends on node mapnik:
- windshaft
- [abaculus](https://github.com/CartoDB/abaculus/releases/1.1.0-cdb5)
- [tilelive-bridge](https://github.com/CartoDB/tilelive-bridge/releases/1.3.0-cdb5)
- [mapnik-pool](https://github.com/CartoDB/mapnik-pool/releases/0.1.1-cdb5)
- [tilelive-mapnik](https://github.com/CartoDB/tilelive-mapnik/release/0.6.15-cdb7)
I'd like to merge this, close and tag this version `1.19.1` (and open a new stub one) and proceed with the changes and deploy of windshaft-cartodb. Can I proceed, @rochoa ?

Upgrade mapnik to 1.4.15-cdb8

---

test/integration/static_maps.js

Connection params should be driven by env configuration
Fixes 8 tests over 14 failing as reported in #495

Do not enforce a dbuser in connection

---

lib/windshaft/metadata/mapnik-layer-metadata.js

.. instead of extracting table names from the query (which is known
to not always yeld the correct result, especially when the query
uses functions to fetch data)
Also helps reducing dependency on cartodb-postgresql for deploys
with controlled MapConfig editing (see #503)
NOTE: this was tested on a live system, but the PR does not contain an automated test

Use "affected_table" in mapnik layer option when available

---

NEWS.md
package.json

- Update cartodb-psql to version [0.7.1](https://github.com/CartoDB/node-cartodb-psql/releases/tag/0.7.1)

Version 2.7.0

---

.travis.yml
package.json

To prepare next mayor release we must drop support for Node v0.10.x
cc/ @rochoa

Drop support for Node v0.10

---

NEWS.md
package.json

[LIMITS] Response timeout limit

---

Dockerfile
package.json

Expose node debug port (5858) to host to allow easier debugging

Enable docker debugging by exposing Node debug port to host

---

lib/windshaft/renderers/pg-mvt/renderer.js

Fix scale denominator token substitution to take care of `cdb_XYZ_Resolution` return type

Fix PostGIS MVT query

---

lib/windshaft/renderers/pg-mvt/factory.js
lib/windshaft/renderers/pg-mvt/renderer.js

This PR fix 2 buffersize problems:
- It fixes the SQL query to expand the bounding box by using the buffersize
- It fixes the pg-mvt factory to get the mapConfig buffersize value
Additionally, it fixes the query substitution for tiles with sizes different than 256 pixels.

MVT buffersize fix

---

.travis.yml
NEWS.md
README.md
docker-test.sh
examples/http/server.js
lib/windshaft/index.js
lib/windshaft/renderers/blend/factory.js
lib/windshaft/renderers/blend/renderer.js
lib/windshaft/renderers/http/renderer.js
lib/windshaft/renderers/mapnik/factory.js
lib/windshaft/renderers/plain/color_renderer.js
lib/windshaft/renderers/plain/factory.js
lib/windshaft/renderers/plain/image_renderer.js
package.json
test/acceptance/layer-filtering-regressions.js
test/acceptance/multilayer.js
test/acceptance/mvt.js
test/acceptance/server_gettile.js
test/acceptance/static_maps.js
test/acceptance/vector-layergroup.js
test/acceptance/zoom-min-max.js
test/integration/renderers/plain_image_renderer.js
test/integration/static_maps.js
test/support/assert.js
test/support/server_options.js
test/support/test_client.js

New features:
- Now mapnik has support for fine-grained metrics.
- Variables can be passed for later substitution in postgis datasource.
Announcements:
- Upgrade mapnik to @carto/mapnik 3.6.2-carto.1, which uses carto lib mapnik v3.0.15.2 underneath. See https://github.com/CartoDB/mapnik/blob/v3.0.15-carto/CHANGELOG.carto.md and https://github.com/CartoDB/mapnik/blob/v3.0.15-carto/CHANGELOG.carto.md
- Upgrade tilelive-bridge to @carto/tilelive-bridge 2.5.1-cdb1. See https://github.com/CartoDB/tilelive-bridge/blob/cdb-2.x/CHANGELOG.carto.md
- Upgrade tilelive-mapnik to 0.6.18-cdb4
- Upgrade abaculus to 2.0.3-cdb2
- Upgrade grainstore to 1.8.1
- Use yarn instead of npm
- Use the script docker-test.sh for travis builds

Upgrade mapnik 3.6.2 carto.1

---

package.json

Solving a part of https://github.com/CartoDB/Windshaft-cartodb/issues/819
Main PR https://github.com/CartoDB/Windshaft-cartodb/pull/849
Updating node-redis package adding Redis 4 support
Of course, this change must be work with Redis 3.

supporting redis4

---

NEWS.md
lib/windshaft/renderers/mapnik/adaptor.js

Turns something like this:
```
{
render:17,
encode:7,
Mapnik:{
'Time (us)':16617,
Calls:1,
Setup:{
'Time (us)':3671,
Calls:1,
'Datasource: Get Features':{
'Time (us)':3643,
Calls:1
}
},
Render:{
'Time (us)':11206,
Calls:1,
Style:{
'Time (us)':11200,
Calls:1,
features:246
}
}
}
}
```
Into something like this:
```
{
render:17,
encode:7,
Mk_Setup:3.671,
Mk_Render:11.206,
Mk_FeatNum:246
}
```
This is needed for 2 reasons:
* Decrease the size of the payload in the header (which was an extra ~200B per tile).
* Compatibility with logstash / ElasticSearch.

Adapt Mapnik metrics into single objects

---

NEWS.md
lib/windshaft/renderers/mapnik/adaptor.js
package.json
test/acceptance/raster.js

https://github.com/CartoDB/Windshaft/pull/594 only applied the transformation when using onTileErrorStrategy with png. This adds it when !onTileErrorStrategy and for grid.json.
Also updates tests to check all formats.

Mapnik metrics: Apply top metrics to all possibilities

---

NEWS.md
lib/windshaft/backends/attributes.js
package.json
run_tests.sh
test/acceptance/attributes.js

The idea is that if there are several points in the map in the same position but all have the same attributes (for the requested columns) we'll return those common attributes instead of an error. If the attributes are different we'd still return an error. 
Related to https://github.com/CartoDB/support/issues/1298
Also re-enables test cleanup that I pushed by mistake.

 AttributesBackend: Allow multiple points if all the attributes are  the same 

---

NEWS.md
lib/windshaft/backends/attributes.js
test/acceptance/attributes.js

Related to https://github.com/CartoDB/support/issues/1380
Since there is no comparison operator for json objects in Postgresql, the DISTINCT with json_agg failed, so I've moved the comparisons to js instead of the query.

AttributesBackend: Support distinct and json_agg

---

NEWS.md
lib/windshaft/renderers/mapnik/adaptor.js
test/acceptance/raster.js

Related to https://github.com/CartoDB/support/issues/1374
When partial metrics were returned from Mapnik (due to not rendering anything for example) an error appeared as it tried to read from an undefined object

Fix bug when parsing incomplete Mapnik metrics

---

NEWS.md
package.json

Update `@carto/mapnik` and all dependencies that in turn depend on it to
that version.
It brings a cache for rasterized symbols.
Also bump package minor version and update NEWS.md
cc'ing @Algunenano and @dgaubert mostly for awareness. Here's my plan for this:
- Get as much as I can ready in advance about packaging, to be able to deploy at a press of a button. This is almost the last step.
- Get some prod metrics to compare against.
- Deploy and check metrics
- Celebrate with the victory dance :man_dancing:

Update @carto/mapnik to 3.6.2-carto.4

---

doc/metrics.md
test/acceptance/metrics.js

Extra notes:
- Adds a disabled test for metatiles. Pending fix in tilelive-mapnik to enable it.
- Adds a disabled test with render time variables in the `sql`. Pending fix in tilelive-mapnik to enable it.
- Adds a disabled test for the Group Symbolizer. The `carto` module currently doesn't support, but I prefer to have it there for reference.
- The symbolizer tests could do something fancier than:
`assert(stats.hasOwnProperty('Mk_Agg_PGroupS') || stats.hasOwnProperty('Mk_Grid_PGroupS'));`,
like `assert(stats.hasOwnProperty('Mk_' + renderer + '_PGroupS') `, but I prefer this way as it leaves the whole metric name intact in case someone greps the source files looking for it.

Add Mapnik metrics docs and extra tests

---

run_tests.sh
run_tests_docker.sh
test/acceptance/mvt.js
test/acceptance/vector-layergroup.js
test/acceptance/zoom-min-max.js
test/prepare_test

Changes the behaviour to use `POSTGIS_VERSION` as Major * 10000 + Minor * 100 + Patch and make the detection automatic. Examples:
* `2.4.5` - 20405
* `2.2.1`- 20201
* `2.5.0beta1dev` - 20500

Make POSTGIS_VERSION detection automatic

---

test/acceptance/torque_zero_zero.js

Attempt to fix https://github.com/CartoDB/Windshaft/issues/629 so it doesn't depend on the proj release

Torque 0,0 test: Remove srid transformation

---

lib/windshaft/backends/map_validator.js

This is a quick fix for #639
sql_raw presence indicates aggregation or other complex query wrapping is in place.
In these cases running a query with a whole-earth bbox as the attribute validation does can be very expensive (even with LIMIT 1, because the whole table must first be aggregated).
So here we avoid the problematic attribute validation altogether when sql_raw is present.
In particular, notice that:
* If no aggregations or other sql wrapping occurs, no sql_raw is present and validation is not skipped
* If aggregations are requested but they are not being applied (too few rows or wrong geometry type) sql_raw is also empty and validation is not skipped
We'll work on a better solution in #642

Skip attribute validation when sql_raw is present

---

test/acceptance/torque.js

Same as https://github.com/CartoDB/Windshaft-cartodb/pull/1005 but for Windshaft

Tests: Use "UNION ALL" instead of "UNION" to improve performance

---

NEWS.md
lib/windshaft/renderers/pg-mvt/factory.js
lib/windshaft/renderers/pg-mvt/renderer.js
lib/windshaft/renderers/renderer_factory.js
package.json
test/acceptance/limits.js
test/prepare_test

Since you need to open a new connection to close a running query I had to move the connection parameters to the renderer, so I decided to move `getLayerColumns` too and add a `initDB` function to avoid handling promises in the constructor.
To get the limits inside this renderer I've modified the factory to add `mapnik.mapnik.limits` to `mvt`, which is not pretty but needed for compatibility.
Closes #577 
Closes #624

pg-mvt: Implement timeout in getTile

---

lib/windshaft/renderers/pg-mvt/renderer.js
test/acceptance/mvt.js

This removes the trailing semicolon from the input query so that it can be composed in subqueries, just like mapnik renderer does internally.

pg-mvt: ignore semicolon

---

NEWS.md
package-lock.json
package.json

Related to CartoDB/node-cartodb-psql#38 and similar to what was done for the SQL API.

Update cartodb-psql to version 0.13.1

---

lib/windshaft/metadata/layer-metadata.js

As windshaft-cartodb expects when there is no layer metadata

Return empty array instead of null

---

lib/windshaft/renderers/pg-mvt/renderer.js

That parameter is not needed. As per the documentation:
> geom_name is the name of the geometry column in the row
> data. Default is the first geometry column.
This will let us push-down the whole ST_AsMVT expression to foreign
servers through FDW's.

Remove unneeded `the_geom_webmercator` param from ST_AsMVT

---

NEWS.md
lib/windshaft/storages/mapstore.js
package-lock.json
package.json

Related to https://github.com/CartoDB/support/issues/2177
The idea is to put this in production, gather stats and then remove it. Do you think I should do it with a more general-purpose?

Logging redis errors of MapStore
